# https://squidfunk.github.io/mkdocs-material
site_name: CMF3
remote_branch: docs
repo_url: https://github.com/clustermod/CMF3
copyright: Copyright &copy; 2019 - 2024 Eric

extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/6Sq6hDgbGF
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@clustercommunity5241
  
  prefix: cmf
  version:
    release:
      download_url: https://github.com/clustermod/CMF3/releases/latest
      major: 2
      minor: 1
      patch: 0

nav:
  - Home: index.md
  - Wiki: wiki/index.md
  - CMF3 Contributors: contributors.md

extra_css:
  - styles.css
theme:
  name: material
  custom_dir: docs/overrides
  favicon: img/logo/favicon.png
  logo: img/logo/cmf3_logo_trans.png
  font:
    text: Open Sans
  palette:
    scheme: default
    primary: black
    accent: indigo
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs.sticky
    - navigation.tabs
    - navigation.path
    - navigation.footer
    - navigation.top
    - content.code.copy
    - content.code.annotate

plugins:
  - macros:
        module_name: docs/macros

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.keys
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg